chat/urls.py
from django.urls import include, re_path, path
from . import views

#This re_path is url for Django 4.0+, works with old format
urlpatterns = [
    re_path(r'^$', views.all_rooms, name="all_rooms"),
    re_path(r'token$', views.token, name="token"),
    re_path(r'rooms/(?P<slug>[-\w\d.@%]+)/$', views.room_detail, name="room_detail"),
]

studdybuddy/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from chat import views as chat_views
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('', include(('chat.urls', 'chat'), namespace='chat')),
    #path(),
    # path("", include("matching.urls")), # now http://127.0.0.1:8000/ will also take the urls created in matching
    path('pairs/', include('pairs.urls')),
    path('admin/', admin.site.urls),
    path("dashboard/", views.dashboard_view, name="dashboard"), # this is where people can see their dashboard - ex: what their classes are, their messages, their friends, etc.
    # path('login/', views.login, name="login"), # going to http://127.0.0.1:8000/login/ will direct you to a page that says you're logged in 
    # path('login/', TemplateView.as_view(template_name="index.html"), name="index"), 
    path("accounts/", include("django.contrib.auth.urls")),
    path('accounts/', include('allauth.urls')),
    path('home/', views.logout_view, name="logout"),
    path('edit_profile/', views.edit_profile_view, name="edit_profile"), 
    path('view_profile/', views.profile_view, name='view_profile'), # HERE 
    path('create_profile/', views.create_profile_view, name='create_profile'),
    path('edit_classes/', views.edit_classes_view, name="edit_classes"),
    path('code_of_conduct/', views.code_of_conduct_view, name='code_of_conduct'),
    path('about/', views.about_view, name='about'),
    path("profile_list/", views.profile_list, name="profile_list"), # this is where people can see other people's profiles for their specified class
    path("profile/<int:pk>", views.matchingprofile, name="matchingprofile"), # this is where people can see their profile and hopefully have the option to edit 
    path('forum/', views.forum, name='forum'),
    path('forum/<str:room>/', views.room, name='room'),
    path('send', views.send, name='send'),
    path('getMessages/<str:room>/', views.getMessages, name='getMessages'),
    path('createsession/', views.create_study_session, name='createstudysession'),
    path('sessions/', views.sessions_view, name='sessions'),
]

studdybuddy/models.py
from email.policy import default
from django.db import models
from datetime import datetime


class Room(models.Model):
    name = models.CharField(max_length=1000)


class Message(models.Model):
    value = models.CharField(max_length=1000000)
    date = models.DateTimeField(default=datetime.now, blank=True)
    user = models.CharField(max_length=1000000)
    room = models.CharField(max_length=1000000)


class Profile(models.Model):
    class Year(models.TextChoices):
        FIRST_YEAR = "First Year"
        SECOND_YEAR = "Second Year"
        THIRD_YEAR = "Third Year"
        FOURTH_YEAR = "Fourth Year"

    first_name = models.CharField(max_length=25, default="")
    last_name = models.CharField(max_length=25, default="")
    email = models.CharField(max_length=50, default="")
    pronouns = models.CharField(max_length=15, default="")
    year = models.CharField(max_length=11, choices=Year.choices, default="")
    major = models.CharField(max_length=30, default="")
    bio = models.CharField(max_length=560, default="")

    def __str__(self):
        return "First name: {} Last name: {} Email: {} Pronouns: {} Year: {} Major: {} Bio: {}".format(self.first_name,
                                                                                                       self.last_name,
                                                                                                       self.email,
                                                                                                       self.pronouns,
                                                                                                       self.year,
                                                                                                       self.major,
                                                                                                       self.bio)

class Course(models.Model):
    name = models.CharField(max_length=9)
    profile = models.ForeignKey(to=Profile, on_delete=models.CASCADE, related_name="courses", default=1)


class StudyDate(models.Model):
    participants = models.ManyToManyField(Profile)
    course = models.CharField(max_length=50, default="")
    month = models.CharField(max_length=25, default="")
    day = models.IntegerField(null=True)
    hour = models.IntegerField(null=True)
    minute = models.IntegerField(null=True)
    year = models.IntegerField(null=True)
    description = models.CharField(max_length=100, default="")


    def __str__(self):
        return "{} study session on {}. {}, {} at {}:{}".format(self.course,    
                                                                self.month,
                                                                self.day,
                                                                self.year,
                                                                self.hour,
                                                                self.minute
                                                                )

studdybuddy/views.py
import email
from re import template
from django.http import Http404, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.urls import reverse
from .models import Profile, Room, Message, Course, StudyDate
from .forms import ProfileForm, ProfileViewForm, StudyDateForm
from django.contrib.auth.models import User
from django.views import generic
from studdybuddy import course_list
from django import forms

class CourseProfile:
    def __init__(self, profile):
        self.profile = profile
        self.courses = profile.courses.all()

def create_profile_view(request):
    error = ""
    if request.method == "POST":
        form = ProfileForm(request.POST)
        if form.is_valid():
            # retrieve email from hidden input field
            email = request.POST.get("email", "")
            # set profile with that email
            form.email = email
            # fails if profile with that email already exists
            if form.email_save() == 0:
                error = "User with this email already exists, please use a different Google login"
                return render(request, "studdybuddy/create_profile.html", {"form": form, "error": error})
            # else first profile with that email, saves and shows profile view
            else:
                return HttpResponseRedirect(reverse('dashboard'))
        else:
            print(form.errors)
    else:
        form = ProfileForm()
    return render(request, "studdybuddy/create_profile.html", {"form": form, "error": error})


def create_study_session(request):
    error = ""
    profile = Profile.objects.get(email=request.user.email)
    courses = profile.courses.all()
    if request.method == "POST":
        form = StudyDateForm(request.POST, initial={'participants': profile})
        # make sure all fields are filled out
        if (form.is_valid()):
            # make sure the user making the session is in the session
            if (str(profile.pk) in request.POST.getlist("participants")):
                # make sure there are more than one participants
                if (len(request.POST.getlist("participants")) > 1):
                    form.save()
                    return HttpResponseRedirect(reverse('dashboard'))
                else:
                    error = "You must include at least one other student in the session"
            else:
                error = "You must include yourself in the study session"
        else:
            error = "Please fill out all fields before submitting"
    else:
        form = StudyDateForm(initial={'participants': profile})
    return render(request, "studdybuddy/create_study_sess.html", {"form": form, "courselist": courses, "error": error})


def sessions_view(request):
    profile = Profile.objects.get(email=request.user.email)
    courses = profile.courses.all()
    dates = StudyDate.objects.exclude(participants=profile)
    errorMsg = "No sessions found for that class"
    if request.method == "GET":
        selected = request.GET.get("selected", "")
        for date in dates:
            if selected == date.course:
                errorMsg = ""
    if request.method == "POST":
        dateDesc = request.POST.get("date", "")
        date = StudyDate.objects.get(description=dateDesc)
        date.participants.add(profile)
        date.save()
        return HttpResponseRedirect(reverse('dashboard'))
    return render(request, "studdybuddy/sessions_list.html", {"dates": dates, "profile": profile,
                                                                  "courses": courses, "selected": selected, "error": errorMsg})


def dashboard_view(request):
    profile = Profile.objects.get(email=request.user.email)
    dates = profile.studydate_set.all()
    ordering = ['-date_created']
    return render(request, "studdybuddy/dashboard.html", {"profiles": profile, "dates": dates})


def logout_view(request):
    logout(request)
    return render(request, "studdybuddy/index.html")

def profile_view(request):
    try:
        instance = Profile.objects.get(email=request.user.email)
        form = ProfileViewForm(instance=instance)
        # makes the fields readonly and disabled
        form.fields['first_name'].widget.attrs['readonly'] = True
        form.fields['last_name'].widget.attrs['readonly'] = True
        form.fields['email'].widget.attrs['readonly'] = True
        form.fields['pronouns'].widget.attrs['readonly'] = True
        form.fields['year'].widget.attrs['readonly'] = True
        form.fields['major'].widget.attrs['readonly'] = True
        form.fields['bio'].widget.attrs['readonly'] = True        
        form.fields['first_name'].widget.attrs['disabled'] = True
        form.fields['last_name'].widget.attrs['disabled'] = True
        form.fields['email'].widget.attrs['disable'] = True
        form.fields['pronouns'].widget.attrs['disabled'] = True
        form.fields['year'].widget.attrs['disabled'] = True
        form.fields['major'].widget.attrs['disabled'] = True
        form.fields['bio'].widget.attrs['disabled'] = True
    except Profile.DoesNotExist:
        raise Http404("Profile does not exist")
    return render(request, 'studdybuddy/view_profile.html', {'form': form})

def edit_profile_view(request):
    # retrieve profile using social account email
    instance = Profile.objects.get(email=request.user.email)
    # if user clicks save, try to save profile
    if request.method == "POST":
        form = ProfileForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
        else:
            print(form.errors)
        return HttpResponseRedirect(reverse('view_profile'))
    # else display profile forms prepopulated with current form info
    else:
        form = ProfileForm(instance=instance)
        # make email readonly
        form.fields['email'].widget.attrs['readonly'] = True
        form.fields['email'].widget.attrs['disabled'] = True
    return render(request, "studdybuddy/edit_profile.html", {"form": form})


def edit_classes_view(request):
    profile = Profile.objects.get(email=request.user.email)
    courselist = course_list.getCourseList()
    courses = profile.courses.all()
    if request.method == "POST":
        # first remove all courses
        profile.courses.all().delete()
        # next add all courses from the page to the profile
        first = True
        # iterate over course list and add each course to profile
        for course in request.POST:
            # don't include csrf token
            if not first:
                newCourse = Course(name=course, profile=profile)
                newCourse.save()
            first = False
        courses = profile.courses.all()
    return render(request, "studdybuddy/edit_classes.html", {"courses":courses, "courselist": courselist}) 


def code_of_conduct_view(request):
    base_template = "studdybuddy/base.html"
    # check if a user with this email exists
    try:
        Profile.objects.get(email=request.user.email)
    # if profile with this email doesn't exist
    except Profile.DoesNotExist:
        no_profile = 1
        base_template = "studdybuddy/partial_base.html"
    # else profile already exists
    else:
        no_profile = 0
    return render(request, 'studdybuddy/code_of_conduct.html', {"no_profile": no_profile, "base_template":base_template})


def about_view(request):
    return render(request, 'studdybuddy/about.html')


def profile_list(request):
    # retrieve objects from profile table and store them in variable "profiles"; we exclude our own
    profile = Profile.objects.get(email=request.user.email)
    courses = profile.courses.all()
    other_profiles = Profile.objects.exclude(email=request.user.email) 
    profiles = []
    for p in other_profiles:
        profiles.append(CourseProfile(p))
    return render(request, "studdybuddy/profile_list.html", {"profiles": profiles, "courses": courses}) 


def matchingprofile(request, pk):
    try:
        profile = Profile.objects.get(pk=pk)
        form = ProfileViewForm(instance=profile)
        # makes the fields readonly
        form.fields['first_name'].widget.attrs['readonly'] = True
        form.fields['last_name'].widget.attrs['readonly'] = True
        form.fields['email'].widget.attrs['readonly'] = True
        form.fields['pronouns'].widget.attrs['readonly'] = True
        form.fields['year'].widget.attrs['readonly'] = True
        form.fields['major'].widget.attrs['readonly'] = True
        form.fields['bio'].widget.attrs['readonly'] = True
    except Profile.DoesNotExist:
        raise Http404("Profile does not exist")
    return render(request, "studdybuddy/profile.html", {"profile": profile, "form": form})


def forum(request):
    errorMsg = ""
    profile = Profile.objects.get(email=request.user.email)
    courses = profile.courses.all()
    other_profiles = Profile.objects.exclude(email=request.user.email) 
    profiles = []
    for p in other_profiles:
        profiles.append(CourseProfile(p))
    if request.method == "POST":
        username = request.POST.get('username')
        if (username != ""):
            room = request.POST.get('room_name')
            if Room.objects.filter(name=room).exists():
                return redirect(room + '/?username=' + username)
            else:
                new_room = Room.objects.create(name=room)
                new_room.save()
                return redirect(room + '/?username=' + username)
        else:
            errorMsg = "You must enter a username"
    return render(request, 'studdybuddy/forum.html', {"profiles": profiles, "courses": courses, "error": errorMsg})

def room(request, room):
    username = request.GET.get('username')
    room_details = Room.objects.get(name=room)
    return render(request, 'studdybuddy/room.html', {
        'username': username,
        'room': room,
        'room_details': room_details
    })

def send(request):

studdybuddy/templates/studdybuddy/base.html
<!DOCTYPE html>
<html lang="en">

    <head>
        {% load static %}
        {% load socialaccount %}
        <title> {% block title %}Studdy Buddy{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'studdybuddy/styles/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'studdybuddy/styles/bootstrap.min.css' %}">
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon-16x16.png' %}">
    </head>

    <body>
      <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
              <h5 class="navbar-brand brand">Studdy Buddy</h5>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav me-auto">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'profile_list' %}">Find Buddies</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'sessions' %}">Study Sessions</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link"  href="{% url 'chat:all_rooms' %}">Chats</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'forum' %}">Class Forums</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">About</a>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="{% url 'about' %}">About Studdy Buddy</a>
                      <a class="dropdown-item" href="{% url 'code_of_conduct' %}">Code of Conduct</a>
                    </div>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Settings</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li><a class="dropdown-item" href="{% url 'view_profile' %}">Profile</a></li>
                      <li><a class="dropdown-item" href="{% url 'edit_classes' %}">Edit Classes</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
        </header>

        <section>
          <div class="body-container">
          {% block content %}
          {% endblock %}

              </ol>
              <small class="justify-content-end" style="color: white;">
                  CS 3240: Group B-05 &copy; 2022
              </small>
            </div>
        </section>
          </nav>
        </footer> 
    </body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <script src="{% static 'studdybuddy/scripts/main.js' %}"></script>
</html>

studdybuddy/templates/studdybuddy/code_of_conduct.html
{% extends base_template %}

{% block content %}
    <div class="profile-form-container">
        <title>Code of Conduct</title>
        <h1>
            Code of Conduct
        </h1>
        <h2>
            Engagement & Community Rules
        </h2>

        <ul>
            <li>Treat all users and colleagues fairly and equally. Stimulate conversation, be respectful of others' views, and refrain 
                from personal attacks.</li>
            <li>Don't share the posts of others without permission.</li>
        </ul>
        <h2>
            Etiquette
        </h2>
        <ul>
            <li>All defamatory, abusive, profane, threatening, offensive, or illegal material is strictly prohibited.</li>
            <li>Discriminatory, hostile, or intimidating messages or language will not be tolerated, whether based on a person's race, 
                ethnicity, culture, national origin, social or economic class, educational level, sex, sexual orientation, gender 
                identity and expression, age, size, family status, political belief, religion, or mental or physical ability.</li>
            <li>Studdy Buddy strives to create and maintain a community in which people of many different backgrounds and cultures are 
                treated with respect.</li>
            <li>Be mindful and respectful of linguistic background &mdash; while the language for online fora discussions is mostly 
                English (unless otherwise specified), remember not everybody is a native English speaker/writer.</li>
            <li>Include only relevant portions of the original message in replies.</li>
            <li>Avoid administrative messages, such as removing me from the session (use the web interface to change your personal 
                settings).</li>
            <li>Do not spam messages.</li>
            <li>Don't publicly post messages.</li>
            <li>Use caution when discussing. The information posted on the lists and in the libraries is available for all members to 
                see. </li>
        </ul>
        <h2>
            Privacy Policy
        </h2>
        <p>
            Studdy Buddy is committed to respecting the privacy of our members and of visitors to our site. We do not sell, rent, 
            or share any personally identifiable information shared by members.
        </p>
        {% if no_profile %}
        <h4>
            By continuing to create your profile, you are agreeing to the Code of Conduct
        </h4>
        <a href="{% url 'create_profile' %}"><button class="btn btn-primary">Accept and Create Profile</button></a>
        {% endif %}
    </div>

    <!-- Beginning of footer -->
    </div>
    </section>

    <footer>
    <nav class="navbar fixed-bottom navbar-dark bg-primary">
        <div class="container-fluid">
        <ol class="breadcrumb justify-content-end">
            {% if no_profile %}
            <li class="breadcrumb-item active">Dashboard</li>
            {% else %}
            <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Dashboard</a></li>
            {% endif %}
            <li class="breadcrumb-item active">Code of Conduct</li>
{% endblock %}

studdybuddy/templates/studdybuddy/create_profile.html
{% extends "studdybuddy/partial_base.html" %}
{% block content %}

<div class="profile-form-container" style="margin: auto;">
    <h3>Make Your Profile</h3>
    {% if error %}
        <div class='alert alert-warning'>{{ error }}</div>
    {% endif %}
    <div class="container">  
      <form method="post">
      {% csrf_token %}
      <div class="row"> 
        <div class="col-md-3 text-end">
          <p class="create-profile-field">
          First Name:
          </p>
          <p class="create-profile-field">
          Last Name:
          </p>
          <p class="create-profile-field" style="margin-bottom: 0;">
          Preferred Pronouns:
          </p>
          <p style="margin-top: 25px;">
          Year:
          </p>
          <p style="margin-top: 24px;">
          Major:
          </p>
          <p style="margin-top: 45px;">
          Bio:
          </p>
        </div>
        <div class="col-md-8">
          {{form.first_name}}
          <br>
          {{form.last_name}}
          <br>
          {{form.pronouns}}
          <br>
          {{form.year}}
          <br>
          {{form.major}}
          <br>
          {{form.bio}}
          <br>
        </div>
      </div> 
      <input type="hidden" name="email" value="{{ user.email }}">
      <div class="text-center">
        <button class="btn btn-primary" type="submit">Submit</button>
      </div>
      </form>
    </div>
</div>

<!-- Beginning of footer -->
</div>
</section>

<footer>
  <nav class="navbar fixed-bottom navbar-dark bg-primary">
    <div class="container-fluid">
      <ol class="breadcrumb justify-content-end">
        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Dashboard</a></li>
        <li class="breadcrumb-item active">Create Profile</li>
{% endblock %}

studdybuddy/templates/studdybuddy/forum.html
{% extends "studdybuddy/base.html" %}
{% block content %}


<!-- <div style="text-align: center;"> -->
    <h2>Enter A Class Forum</h2>
<!-- </div> -->

<p>Class forums are meant to be places to discuss classes and class content and ask and answer questions. All other users who 
  enter the class forum can see your messages, so be sure you are following StuddyBuddy's Code of Conduct! 
</p>
{% if error %}
  <div class="alert alert-warning" role="alert">{{ error }}</div>
{% endif %}
<div class="container">
  <div class="row">
    <div class="col-md-5">
      <form method="post" action="{% url 'forum' %}">
        {% csrf_token %}
        <div class="mb-3">
          <h5>Select the class you want to study for:</h5>
          <input class="form-control" list="course-list" id="searchbar" onkeyup="profileSearch()" name="room_name" placeholder="Click to see your courses or search (i.e. CS 3240)">
          <datalist id="course-list">
            {% for course in courses %}
              <option style="max-width: 200px" value="{{ course.name }}">
            {% endfor %}
          </datalist>
        </div>
        <div class="mb-3">
          <label for="username">Enter a username:</label>
          <h6>Your username is what will be displayed to other users.</h6>
          <input type="text" name="username" id="username" class="form-control">
        </div>
        <!-- <input type="submit" value="Enter Room"> -->
        <button type="submit" class="btn btn-primary">Enter Room</button>
      </form>
    </div>
    
    <div class="col-md-1"></div>

    <div class="col-md-4">
      <h5>Other students in this class:</h5>
      <div class="alert alert-warning" id="none-found" role="alert" style="display: none;"></div>
      <ul id="profile-list">      
        {% for obj in profiles %}
        <li class="profile-card" style="display: none; margin-bottom: 20px;">  
          {% for course in obj.courses %}
            <input type="hidden" value="{{ course.name }}" class="hidden-course">
          {% endfor %}
          <form method="post" action="{% url 'chat:all_rooms' %}">
          {% csrf_token %}
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{ obj.profile.first_name }} {{ obj.profile.last_name }}</h5>
              <h6 class="card-subtitle mb-2 text-muted">{{ obj.profile.pronouns }}</h6>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">{{ obj.profile.year }}</li>
                <li class="list-group-item">{{ obj.profile.major }}</li>
              </ul>
              <a href="{% url 'matchingprofile' obj.profile.id %}" class="card-link">View profile</a>
              <input type="hidden" name="email" value="{{ obj.profile.email }}">
            </div>
          </div>
          </form>
        </li>
      {% endfor %}
      </ul>
    </div>
  </div>
</div>


<!-- Beginning of footer -->
</div>
</section>

<footer>
  <nav class="navbar fixed-bottom navbar-dark bg-primary">
    <div class="container-fluid">
      <ol class="breadcrumb justify-content-end">
        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Dashboard</a></li>
        <li class="breadcrumb-item active">Class Forums</li>
{% endblock %}

studdybuddy/templates/studdybuddy/profile_list.html
{% extends "studdybuddy/base.html" %}
{% block content %}

<h2>Find Buddies</h2>
<div class="container">
  <div class="row">
    <div class="col-md-5">
    <h5>Select the class you want to study for:</h5>
    <input class="form-control" list="course-list" id="searchbar" onkeyup="profileSearch()" placeholder="Click to see your courses or search (i.e. CS 3240)">
    <datalist id="course-list">
      {% for course in courses %}
        <option style="max-width: 200px" value="{{ course.name }}">
      {% endfor %}
    </datalist>
    </div>

    <div class="col-md-1"></div>

    <div class="col-md-4">
      <h5>Start a chat with someone in your class:</h5>
      <div class="alert alert-warning" id="none-found" role="alert" style="display: none;"></div>
      <ul id="profile-list">      
        {% for obj in profiles %}
        <li class="profile-card" style="display: none; margin-bottom: 20px;">  
          {% for course in obj.courses %}
            <input type="hidden" value="{{ course.name }}" class="hidden-course">
          {% endfor %}
          <form method="post" action="{% url 'chat:all_rooms' %}">
          {% csrf_token %}
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{ obj.profile.first_name }} {{ obj.profile.last_name }}</h5>
              <h6 class="card-subtitle mb-2 text-muted">{{ obj.profile.pronouns }}</h6>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">{{ obj.profile.year }}</li>
                <li class="list-group-item">{{ obj.profile.major }}</li>
              </ul>
              <a href="{% url 'matchingprofile' obj.profile.id %}" class="btn btn-primary">View Full Profile</a>
              <input type="hidden" name="email" value="{{ obj.profile.email }}">
              <button type="submit" class="btn btn-primary">Start Chat</button>
            </div>
          </div>
          </form>
        </li>
      {% endfor %}
      </ul>
    </div>
  </div>
</div>

<!-- Beginning of footer -->
</div>
</section>

<footer>
  <nav class="navbar fixed-bottom navbar-dark bg-primary">
    <div class="container-fluid">
      <ol class="breadcrumb justify-content-end">
        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Dashboard</a></li>
        <li class="breadcrumb-item active">Find Buddies</li>
{% endblock %}